In [2]:
from sklearn.cluster import KMeans
from scipy.io import loadmat
import numpy as np

In [10]:
mat = loadmat('train_data.mat')
train_data = mat['train_data']
#train_labels = mat['train_info'][0, 0]['labels'].reshape(12000, )
#print(train_data.shape, train_labels.shape)
print(train_data.shape)

(12000, 12000)


In [11]:
mat1 = loadmat('test_data.mat')
test_data = mat1['test_data']
#test_labels = mat1['test_info'][0, 0]['labels'].reshape(len(test_data), )
#print(test_data.shape, test_labels.shape)
print(test_data.shape)

(8580, 12000)


In [5]:
X = np.array([[1, 2], [1, 4], [1, 0],[10, 2], [10, 4], [10, 0]])
kmeans = KMeans(n_clusters=2, random_state=0).fit(X)
kmeans.labels_

array([1, 1, 1, 0, 0, 0])

In [6]:
kmeans.predict([[0, 0], [12, 3]])

array([1, 0])

In [7]:
kmeans.cluster_centers_

array([[10.,  2.],
       [ 1.,  2.]])